l_arm_sh_p:
  position_p_gain: 850
  return_delay_time: 10 

l_arm_sh_r:
  position_p_gain: 850
  return_delay_time: 10

l_arm_sh_y:
  position_p_gain: 850
  return_delay_time: 10

l_arm_el_p:
  position_p_gain: 850
  return_delay_time: 10

l_arm_wr_p:
  position_p_gain: 850
  return_delay_time: 10

l_arm_wr_r:
  position_p_gain: 850
  return_delay_time: 10
  
r_arm_sh_p:
  position_p_gain: 850
  return_delay_time: 10 

r_arm_sh_r:
  position_p_gain: 850
  return_delay_time: 10

r_arm_sh_y:
  position_p_gain: 850
  return_delay_time: 10

r_arm_el_p:
  position_p_gain: 850
  return_delay_time: 10

r_arm_wr_p:
  position_p_gain: 850
  return_delay_time: 10

r_arm_wr_r:
  position_p_gain: 850
  return_delay_time: 10

head_yaw:
  position_p_gain: 850
  return_delay_time: 10

head_pitch:
  position_p_gain: 850
  return_delay_time: 10

head_roll:
  position_p_gain: 850
  return_delay_time: 10


