l_arm_shoulder_pitch:
  position_p_gain: 850
  return_delay_time: 10 

l_arm_shoulder_roll:
  position_p_gain: 850
  return_delay_time: 10

l_arm_shoulder_yaw:
  position_p_gain: 850
  return_delay_time: 10

l_arm_elbow_pitch:
  position_p_gain: 850
  return_delay_time: 10

l_arm_wrist_pitch:
  position_p_gain: 850
  return_delay_time: 10

l_arm_wrist_roll:
  position_p_gain: 850
  return_delay_time: 10
  
r_arm_shoulder_pitch:
  position_p_gain: 850
  return_delay_time: 10 

r_arm_shoulder_roll:
  position_p_gain: 850
  return_delay_time: 10

r_arm_shoulder_yaw:
  position_p_gain: 850
  return_delay_time: 10

r_arm_elbow_pitch:
  position_p_gain: 850
  return_delay_time: 10

r_arm_wrist_pitch:
  position_p_gain: 850
  return_delay_time: 10

r_arm_wrist_roll:
  position_p_gain: 850
  return_delay_time: 10

head_yaw:
  position_p_gain: 850
  return_delay_time: 10

head_pitch:
  position_p_gain: 850
  return_delay_time: 10

head_roll:
  position_p_gain: 850
  return_delay_time: 10


