offset:
  l_arm_sh_p: 0
  l_arm_sh_r: 0
  l_arm_sh_y: 0
  l_arm_el_p: 0
  l_arm_wr_p: 0
  l_arm_wr_r: 0
  r_arm_sh_p: 0
  r_arm_sh_r: 0
  r_arm_sh_y: 0
  r_arm_el_p: 0
  r_arm_wr_p: 0
  r_arm_wr_r: 0
  head_yaw: 0
  head_pitch: 0
  head_roll: 0

init_pose_for_offset_tuner:
  l_arm_sh_p: 0
  l_arm_sh_r: 0
  l_arm_sh_y: 0
  l_arm_el_p: 0
  l_arm_wr_p: 0
  l_arm_wr_r: 0
  r_arm_sh_p: 0
  r_arm_sh_r: 0
  r_arm_sh_y: 0
  r_arm_el_p: 0
  r_arm_wr_p: 0
  r_arm_wr_r: 0
  head_yaw: 0
  head_pitch: 0
  head_roll: 0
