offset:
  l_arm_shoulder_pitch: 0
  l_arm_shoulder_roll: 0
  l_arm_shoulder_yaw: 0
  l_arm_elbow_pitch: 0
  l_arm_wrist_pitch: 0
  l_arm_wrist_roll: 0
  r_arm_shoulder_pitch: 0
  r_arm_shoulder_roll: 0
  r_arm_shoulder_yaw: 0
  r_arm_elbow_pitch: 0
  r_arm_wrist_pitch: 0
  r_arm_wrist_roll: 0
  head_yaw: 0
  head_pitch: 0
  head_roll: 0

init_pose_for_offset_tuner:
  l_arm_shoulder_pitch: 0
  l_arm_shoulder_roll: 0
  l_arm_shoulder_yaw: 0
  l_arm_elbow_pitch: 0
  l_arm_wrist_pitch: 0
  l_arm_wrist_roll: 0
  r_arm_shoulder_pitch: 0
  r_arm_shoulder_roll: 0
  r_arm_shoulder_yaw: 0
  r_arm_elbow_pitch: 0
  r_arm_wrist_pitch: 0
  r_arm_wrist_roll: 0
  head_yaw: 0
  head_pitch: 0
  head_roll: 0
